"""update_indexes_and_constraints

Revision ID: ea9069521d16
Revises: 9fd62e8ed3b4
Create Date: 2025-09-25 13:31:38.729822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9069521d16'
down_revision = '9fd62e8ed3b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customers_email', 'customers', type_='unique')
    op.drop_constraint('uq_customers_stripe_customer_id', 'customers', type_='unique')
    op.drop_constraint('uq_customers_user_id', 'customers', type_='unique')
    op.drop_index('ix_customers_email', table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.drop_index('ix_customers_stripe_customer_id', table_name='customers')
    op.create_index(op.f('ix_customers_stripe_customer_id'), 'customers', ['stripe_customer_id'], unique=True)
    op.drop_index('ix_customers_user_id', table_name='customers')
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=True)
    op.drop_index('ix_disputes_stripe_dispute_id', table_name='disputes')
    op.create_index(op.f('ix_disputes_stripe_dispute_id'), 'disputes', ['stripe_dispute_id'], unique=True)
    op.alter_column('invoices', 'stripe_invoice_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_invoices_stripe_invoice_id', table_name='invoices')
    op.create_index(op.f('ix_invoices_stripe_invoice_id'), 'invoices', ['stripe_invoice_id'], unique=True)
    op.drop_index('ix_payments_stripe_payment_intent_id', table_name='payments')
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.drop_index('ix_prices_stripe_price_id', table_name='prices')
    op.create_index(op.f('ix_prices_stripe_price_id'), 'prices', ['stripe_price_id'], unique=True)
    op.drop_index('ix_products_stripe_product_id', table_name='products')
    op.create_index(op.f('ix_products_stripe_product_id'), 'products', ['stripe_product_id'], unique=True)
    op.drop_index('ix_refunds_stripe_refund_id', table_name='refunds')
    op.create_index(op.f('ix_refunds_stripe_refund_id'), 'refunds', ['stripe_refund_id'], unique=True)
    op.drop_index('ix_webhook_events_stripe_event_id', table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_stripe_event_id'), 'webhook_events', ['stripe_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_stripe_event_id'), table_name='webhook_events')
    op.create_index('ix_webhook_events_stripe_event_id', 'webhook_events', ['stripe_event_id'], unique=False)
    op.drop_index(op.f('ix_refunds_stripe_refund_id'), table_name='refunds')
    op.create_index('ix_refunds_stripe_refund_id', 'refunds', ['stripe_refund_id'], unique=False)
    op.drop_index(op.f('ix_products_stripe_product_id'), table_name='products')
    op.create_index('ix_products_stripe_product_id', 'products', ['stripe_product_id'], unique=False)
    op.drop_index(op.f('ix_prices_stripe_price_id'), table_name='prices')
    op.create_index('ix_prices_stripe_price_id', 'prices', ['stripe_price_id'], unique=False)
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.create_index('ix_payments_stripe_payment_intent_id', 'payments', ['stripe_payment_intent_id'], unique=False)
    op.drop_index(op.f('ix_invoices_stripe_invoice_id'), table_name='invoices')
    op.create_index('ix_invoices_stripe_invoice_id', 'invoices', ['stripe_invoice_id'], unique=False)
    op.alter_column('invoices', 'stripe_invoice_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_disputes_stripe_dispute_id'), table_name='disputes')
    op.create_index('ix_disputes_stripe_dispute_id', 'disputes', ['stripe_dispute_id'], unique=False)
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.create_index('ix_customers_user_id', 'customers', ['user_id'], unique=False)
    op.drop_index(op.f('ix_customers_stripe_customer_id'), table_name='customers')
    op.create_index('ix_customers_stripe_customer_id', 'customers', ['stripe_customer_id'], unique=False)
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_unique_constraint('uq_customers_user_id', 'customers', ['user_id'])
    op.create_unique_constraint('uq_customers_stripe_customer_id', 'customers', ['stripe_customer_id'])
    op.create_unique_constraint('uq_customers_email', 'customers', ['email'])
    # ### end Alembic commands ###