name: Sync GSM to Vercel and Deploy

on:
  push:
    branches: [main, dev]
    paths:
      - 'apps/customer/**'
      - 'apps/admin/**'
      - '.github/workflows/sync-gsm-to-vercel.yml'
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  sync-and-deploy-customer:
    name: 🌐 Sync Customer Frontend
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'apps/customer/') || github.event_name == 'workflow_dispatch'

    steps:
      - name: 📁 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 🔑 Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_B64 }}

      - name: 🛠️ Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: 📡 Fetch secrets from GSM
        id: fetch-secrets
        run: |
          # Determine environment based on branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENV="prod"
          else
            ENV="dev"
          fi

          echo "Environment: $ENV"

          # Function to get secret value
          get_secret() {
            local secret_name="$1"
            gcloud secrets versions access latest --secret="$secret_name" --project="${{ env.GCP_PROJECT_ID }}" 2>/dev/null || echo ""
          }

          # Fetch customer frontend secrets
          API_URL=$(get_secret "${ENV}-frontend-web-NEXT_PUBLIC_API_URL")
          AI_API_URL=$(get_secret "${ENV}-frontend-web-NEXT_PUBLIC_AI_API_URL") 
          STRIPE_PUBLIC_KEY=$(get_secret "${ENV}-frontend-web-NEXT_PUBLIC_STRIPE_PUBLIC_KEY")
          GOOGLE_MAPS_KEY=$(get_secret "${ENV}-frontend-web-NEXT_PUBLIC_GOOGLE_MAPS_BROWSER_KEY")
          GTAG_ID=$(get_secret "${ENV}-frontend-web-NEXT_PUBLIC_GTAG_ID")
          SENTRY_DSN=$(get_secret "${ENV}-frontend-web-NEXT_PUBLIC_SENTRY_DSN")

          # Fetch global/shared secrets  
          CONFIG_VERSION=$(get_secret "${ENV}-global-CONFIG_VERSION")

          # Set outputs for next steps
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT
          echo "ai_api_url=$AI_API_URL" >> $GITHUB_OUTPUT
          echo "stripe_public_key=$STRIPE_PUBLIC_KEY" >> $GITHUB_OUTPUT
          echo "google_maps_key=$GOOGLE_MAPS_KEY" >> $GITHUB_OUTPUT
          echo "gtag_id=$GTAG_ID" >> $GITHUB_OUTPUT
          echo "sentry_dsn=$SENTRY_DSN" >> $GITHUB_OUTPUT
          echo "config_version=$CONFIG_VERSION" >> $GITHUB_OUTPUT
          echo "environment=$ENV" >> $GITHUB_OUTPUT

      - name: 🔄 Update Vercel Environment Variables
        run: |
          # Install Vercel CLI
          npm install -g vercel@latest

          # Set environment based on branch
          if [[ "${{ steps.fetch-secrets.outputs.environment }}" == "prod" ]]; then
            VERCEL_ENV="production"
            PROJECT_ID="${{ secrets.VERCEL_PROJECT_ID_CUSTOMER }}"
          else
            VERCEL_ENV="preview"
            PROJECT_ID="${{ secrets.VERCEL_PROJECT_ID_CUSTOMER }}"
          fi

          echo "Updating Vercel environment: $VERCEL_ENV"

          # Function to update env var
          update_env_var() {
            local key="$1"
            local value="$2"
            
            if [[ -n "$value" ]]; then
              echo "Setting $key..."
              echo "$value" | vercel env add "$key" "$VERCEL_ENV" \
                --token="${{ secrets.VERCEL_TOKEN }}" \
                --scope="${{ secrets.VERCEL_ORG_ID }}" \
                --project="$PROJECT_ID" || true
            else
              echo "Skipping $key (empty value)"
            fi
          }

          # Update all environment variables
          update_env_var "NEXT_PUBLIC_API_URL" "${{ steps.fetch-secrets.outputs.api_url }}"
          update_env_var "NEXT_PUBLIC_AI_API_URL" "${{ steps.fetch-secrets.outputs.ai_api_url }}"
          update_env_var "NEXT_PUBLIC_STRIPE_PUBLIC_KEY" "${{ steps.fetch-secrets.outputs.stripe_public_key }}"
          update_env_var "NEXT_PUBLIC_GOOGLE_MAPS_BROWSER_KEY" "${{ steps.fetch-secrets.outputs.google_maps_key }}"
          update_env_var "NEXT_PUBLIC_GTAG_ID" "${{ steps.fetch-secrets.outputs.gtag_id }}"
          update_env_var "NEXT_PUBLIC_SENTRY_DSN" "${{ steps.fetch-secrets.outputs.sentry_dsn }}"
          update_env_var "CONFIG_VERSION" "${{ steps.fetch-secrets.outputs.config_version }}"

      - name: 🚀 Deploy to Vercel
        run: |
          if [[ "${{ steps.fetch-secrets.outputs.environment }}" == "prod" ]]; then
            echo "🎯 Deploying to PRODUCTION"
            vercel --prod \
              --token="${{ secrets.VERCEL_TOKEN }}" \
              --scope="${{ secrets.VERCEL_ORG_ID }}" \
              --project="${{ secrets.VERCEL_PROJECT_ID_CUSTOMER }}"
          else
            echo "🔧 Deploying to PREVIEW"
            vercel \
              --token="${{ secrets.VERCEL_TOKEN }}" \
              --scope="${{ secrets.VERCEL_ORG_ID }}" \
              --project="${{ secrets.VERCEL_PROJECT_ID_CUSTOMER }}"
          fi

  sync-and-deploy-admin:
    name: 🛠️ Sync Admin Frontend
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'apps/admin/') || github.event_name == 'workflow_dispatch'

    steps:
      - name: 📁 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 🔑 Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_B64 }}

      - name: 🛠️ Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: 📡 Fetch admin secrets from GSM
        id: fetch-admin-secrets
        run: |
          # Determine environment
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENV="prod"
          else
            ENV="dev"  
          fi

          # Function to get secret value
          get_secret() {
            local secret_name="$1"
            gcloud secrets versions access latest --secret="$secret_name" --project="${{ env.GCP_PROJECT_ID }}" 2>/dev/null || echo ""
          }

          # Fetch admin frontend secrets
          API_URL=$(get_secret "${ENV}-frontend-admin-NEXT_PUBLIC_API_URL")
          ADMIN_SECRET=$(get_secret "${ENV}-frontend-admin-NEXT_PUBLIC_ADMIN_PANEL_SECRET")
          SENTRY_DSN=$(get_secret "${ENV}-frontend-admin-NEXT_PUBLIC_SENTRY_DSN")

          # Set outputs
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT
          echo "admin_secret=$ADMIN_SECRET" >> $GITHUB_OUTPUT  
          echo "sentry_dsn=$SENTRY_DSN" >> $GITHUB_OUTPUT
          echo "environment=$ENV" >> $GITHUB_OUTPUT

      - name: 🔄 Update Admin Vercel Environment Variables
        run: |
          npm install -g vercel@latest

          if [[ "${{ steps.fetch-admin-secrets.outputs.environment }}" == "prod" ]]; then
            VERCEL_ENV="production"
            PROJECT_ID="${{ secrets.VERCEL_PROJECT_ID_ADMIN }}"
          else
            VERCEL_ENV="preview"
            PROJECT_ID="${{ secrets.VERCEL_PROJECT_ID_ADMIN }}"
          fi

          # Function to update env var
          update_env_var() {
            local key="$1"
            local value="$2"
            
            if [[ -n "$value" ]]; then
              echo "Setting $key..."
              echo "$value" | vercel env add "$key" "$VERCEL_ENV" \
                --token="${{ secrets.VERCEL_TOKEN }}" \
                --scope="${{ secrets.VERCEL_ORG_ID }}" \
                --project="$PROJECT_ID" || true
            fi
          }

          update_env_var "NEXT_PUBLIC_API_URL" "${{ steps.fetch-admin-secrets.outputs.api_url }}"
          update_env_var "NEXT_PUBLIC_ADMIN_PANEL_SECRET" "${{ steps.fetch-admin-secrets.outputs.admin_secret }}"
          update_env_var "NEXT_PUBLIC_SENTRY_DSN" "${{ steps.fetch-admin-secrets.outputs.sentry_dsn }}"

      - name: 🚀 Deploy Admin to Vercel
        run: |
          if [[ "${{ steps.fetch-admin-secrets.outputs.environment }}" == "prod" ]]; then
            vercel --prod \
              --token="${{ secrets.VERCEL_TOKEN }}" \
              --scope="${{ secrets.VERCEL_ORG_ID }}" \
              --project="${{ secrets.VERCEL_PROJECT_ID_ADMIN }}"
          else
            vercel \
              --token="${{ secrets.VERCEL_TOKEN }}" \
              --scope="${{ secrets.VERCEL_ORG_ID }}" \
              --project="${{ secrets.VERCEL_PROJECT_ID_ADMIN }}"
          fi

  notify:
    name: 📢 Deployment Notification
    runs-on: ubuntu-latest
    needs: [sync-and-deploy-customer, sync-and-deploy-admin]
    if: always()

    steps:
      - name: 📨 Send deployment status
        run: |
          if [[ "${{ needs.sync-and-deploy-customer.result }}" == "success" ]] && [[ "${{ needs.sync-and-deploy-admin.result }}" == "success" ]]; then
            echo "✅ All deployments successful!"
            # Add Slack/email notification here if needed
          else
            echo "❌ Some deployments failed"
            # Add error notification here if needed
          fi
