name: 🐛 Bug Report
description: Report a bug or issue
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: []
body:

- type: textarea
  id: bug-description
  attributes:
    label: 🐛 Bug Description
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: 🔄 Steps to Reproduce
    description: Steps to reproduce the behavior
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: ✅ Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  id: actual-behavior
  attributes:
    label: ❌ Actual Behavior
    description: A clear and concise description of what actually happened.
  validations:
    required: true

- type: dropdown
  id: app-component
  attributes:
    label: 🌍 App Component
    description: Which part of the application is affected?
    options:
      - Customer App
      - Admin Dashboard
      - Core API
      - AI API
      - Other
  validations:
    required: true

- type: dropdown
  id: priority
  attributes:
    label: 🚨 Priority Level
    description: How critical is this bug?
    options:
      - Critical (app is unusable)
      - High (major feature broken)
      - Medium (minor feature issue)
      - Low (cosmetic issue)
  validations:
    required: true

- type: textarea
  id: error-messages
  attributes:
    label: 📝 Error Messages
    description: Paste any relevant error messages or logs here
    render: shell

- type: textarea
  id: additional-context
  attributes:
    label: 🔍 Additional Context
    description: Add any other context about the problem here.
