name: AI Backend CI - Simple Fix

on:
  push:
    paths: 
      - 'myhibachi-ai-backend/**'
      - '.github/workflows/ai-backend-simple.yml'
  pull_request:
    paths:
      - 'myhibachi-ai-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Debug repository structure
        run: |
          echo "=== Current working directory ==="
          pwd
          echo "=== List all directories ==="
          find . -type d -name "*hibachi*" | head -10
          echo "=== Find requirements.txt files ==="
          find . -name "requirements.txt" | head -10
          echo "=== Check exact path ==="
          ls -la myhibachi-ai-backend/ 2>/dev/null || echo "myhibachi-ai-backend directory not found"
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          # Remove cache for now to avoid path issues
          
      - name: Install dependencies (manual check)
        run: |
          cd myhibachi-ai-backend 2>/dev/null || { echo "Cannot cd to myhibachi-ai-backend"; exit 1; }
          echo "=== Current directory ==="
          pwd
          echo "=== Files in current directory ==="
          ls -la
          if [ -f "requirements.txt" ]; then
            echo "✅ Found requirements.txt"
            cat requirements.txt
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            echo "✅ Dependencies installed successfully"
          else
            echo "❌ No requirements.txt found"
            echo "Installing basic dependencies..."
            python -m pip install --upgrade pip
            pip install fastapi uvicorn python-multipart pydantic httpx openai
          fi
          
      - name: Verify installation
        working-directory: myhibachi-ai-backend
        run: |
          echo "=== Checking installed packages ==="
          pip list | grep -E "(fastapi|uvicorn|pydantic|httpx|openai)" || echo "Some packages missing"
          echo "=== Testing imports ==="
          python -c "import fastapi; print('✅ FastAPI OK')"
          python -c "import uvicorn; print('✅ Uvicorn OK')"
          python -c "import pydantic; print('✅ Pydantic OK')"
