name: AI Backend CI - Alternative

on:
  push:
    paths: 
      - 'myhibachi-ai-backend/**'
      - '.github/workflows/ai-backend-alt.yml'
  pull_request:
    paths:
      - 'myhibachi-ai-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python (without cache)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        working-directory: myhibachi-ai-backend
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            echo "Found requirements.txt, installing dependencies..."
            cat requirements.txt
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, installing fallback dependencies..."
            pip install fastapi uvicorn python-multipart
          fi
          
      - name: Verify installation
        working-directory: myhibachi-ai-backend
        run: |
          echo "Checking installed packages..."
          pip list | grep -E "(fastapi|uvicorn|pydantic|httpx|openai)"
          
      - name: Run basic validation
        working-directory: myhibachi-ai-backend
        run: |
          echo "Running syntax validation..."
          python -c "import main; print('✅ main.py syntax OK')" || echo "❌ main.py syntax error"
          python -c "import simple_backend_corrected; print('✅ simple_backend_corrected.py syntax OK')" || echo "❌ simple_backend_corrected.py syntax error"
